### ISSUE TITLE
MIS slides

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#24]
Hello,

This is my slide for my next presentation. I'd appreciate your feedback on this.
[MIS.pptx](https://github.com/AtiyehSayadi/Centrality-In-Graphs/files/14467812/MIS.pptx)

**Comment by smiths** [comment]
@AtiyehSayadi that is great that you are trying to get ahead of things by seeking feedback early.  Your attempt is a little early though because we haven't talked about some of the things that you will need for your design.  I'll give you feedback below.  The points should make more sense after our lectures this coming week.

- your file module should have an environment variable for the file
- for a file module there is usually a string input for the filename
- you should write the secret for each module (the secret is the likely change that is encapsulated inside the module)
- rather than represent the graph by an n*n matrix, you likely want a graph module that has the secret of the data structure used to represent the graph
- you might want to have modules for abstract data types related to vertices, edges and the graph.  Whether you have modules for vertices and edges depends on your identified likely changes
- you might have degree and closeness as access programs for your graph module.  If the algorithms are likely changes, then separate modules make sense.  Rather than using the file, you would use your graph module (abstract data type for a graph) as input.  You would use the interface for the graph module, rather than operating directly on your assumed data structure.
- the GUI module should use an environment variable for the screen

I suggest that you look at the interface for existing graph libraries for inspiration.

**Comment by AtiyehSayadi** [comment]
Hello,

Thank you very much for your detailed feedback. I have understood that for the file module, I need to have an input of type string and set a variable to store the file path. Also, for setting the size of the screen in the GUI module, I need another environment variable.

However, I got a bit confused about the module you suggested, which is the graph module. Let me ask you more questions about this. For calculating centrality measures, it is necessary to have the adjacency matrix as input, which remains as a state variable in both modules without any change. How will these calculations be done if we define a graph module? How logical would it be to define a graph module when it won't be used in any of the calculations?

Possible changes include adding calculations for other centrality measures and using a directed graph instead of an undirected graph, which will affect all calculations. Even if we add the graph module (which I'm not sure about using), the output of the file module will still be a matrix.

Is the secret the same as explaining the functionality of the module, or should only potential changes to the module be mentioned?

I would greatly appreciate it if you could guide me on these matters.

Thank you very much.

**Comment by smiths** [comment]
@AtiyehSayadi your questions are partly caused by the fact that we haven't had a lecture yet to discuss the details of the modular design.  Let's wait and see if you still have questions after our upcoming lectures.  

Understanding the idea of a graph module will be easier if you have done object oriented programming before.  The graph module is an abstract data type, like a stack.  The state of the graph will include the adjacency matrix.  You have setters to add edges.  You have getters to return values based on the state of the adjacency matrix.  One getter could be to return the degree of a vertex (node) when given that vertex (node) as input.

**Comment by AtiyehSayadi** [comment]
Hello,

According to your precise explanations, I have modified the MIS slide and sent it to you. I would greatly appreciate your feedback on it.

[MIS.pptx](https://github.com/AtiyehSayadi/Centrality-In-Graphs/files/14504018/MIS.pptx)

**Comment by smiths** [comment]
Quick feedback:

- you shouldn't name your modules by the libraries you are going to use.  You can use the libraries in the implementation, but you should give your modules your own names at this stage.  You want to leave it as an option to create a wrapper for this modules.  You probably won't but it is premature to decide for sure, and this might be a choice that could be modified in the future.
- your file module probably shouldn't have a state variable.  File modules usually populate the state variable of another module.  In  your case the module that file would change the state of is your graph module
- the file module shouldn't know the secret of the graph module.  The file module shouldn't know how to calculate the adjacency matrix.  That is the secret of your graph module.
- you don't need to assume only numeric values.  It is better to have exceptions than assumptions
- your initialization for the graph module should be empty for the input.  You don't know the adjacency matrix.  You build the data in the graph module through your setters.
- you use an init method if your module is an abstract object.  An abstract object is less useful than an abstract data type.  You should use a constructor named after the name of your module to build the initial graph.
- will you ever need get edges as part of your interface?  What does it even mean?  What is the output integer for get_edges?
- Isn't there just one number for degree centrality of each node?  Should the output of degree centrality be of type R^n? (same question for closeness centrality)
- you shouldn't assume a specific programming language for the MIS.  Your state variables shouldn't be self.matrix etc.
- for your state variables for the Graph module you should use the same notation I used in class, and in the examples.  Give the name of the variable followed by a full colon and its type.  The type should be written mathematically.  For instance, a square matrix of natural numbers would be N^{nxn}
- the ands in the secret for the graph module suggest that you might want to split this into two modules.  One for the data structure and one for the algorithms.  If you don't split it, you should have a rationale in your design for that choice
-

**Comment by AtiyehSayadi** [comment]
Hello,
I'm sorry for so many questions.
Based on what I understood from our conversations, I have modified the slides. I would greatly appreciate it if I could have your feedback about new slides.
[MIS.pptx](https://github.com/AtiyehSayadi/Centrality-In-Graphs/files/14544816/MIS.pptx)

**Comment by smiths** [comment]
Quick feedback:

- File Module - don't you know the type T?  Doesn't your file hold the adjacency matrix
- File Module - the secret is the file format, not the location of the file
- File Module - you don't provide the semantics for the read_file method.  It should populate the state of your graph module
- Graph Module - if you are going to have types for NodeT and EdgeT,  you should give a separate module that specifies the abstract data types for NodeT, and another module for EdgeT (I think you might confuse yourself if you go down this road.  You are probably better off creating a graph of a given size n (number of nodes) with the constructor.  You would then not add nodes to the graph, you would only add edges.
- Graph Module - the state variable can't be the ADT you are defining.  You define the actual mathematical representation of the adjacency matrix here.  To make you life simple, you could give the type N^{nxn}; that is an nxn matrix of natural numbers.
- Graph Module - the constructor (your build_graph) should be called GraphT
- Graph Module - the input for the constructor should probably just be the size of your adjacency matrix.  You don't input the adjacency matrix directly, since that is the information you are hiding.
- Graph Module - if you need it, you can have an exist edge method, but the inputs should be two natural numbers - these numbers would be the labels for your nodes
- GUI Module - the access programs shouldn't calculate degree_centrality or closeness_centrality because you already have those from your GraphT module
- GUI Module - the access programs for the GUI module should say how the screen is going to change
