### ISSUE TITLE
SRS slides

### ISSUE THREAD

**Issue by AtiyehSayadi** [AtiyehSayadi/Centrality-In-Graphs#5]
I provided my presentation concepts here.  Please let me know your idea about that.
[SRS.pptx](https://github.com/AtiyehSayadi/Centrality-In-Graphs/files/14107030/SRS.pptx)

**Comment by smiths** [comment]
Feedback:

- on slide 2 say "in a graph" rather than "in the graph"
- the examples are nice and the equations are well described
- I'd like to see a formal representation of a graph
- I'd like to see a formal expression for shortest path
- I'd like to see a formal expression for degree of a node
- I'd like to see an example of your input (the connections graph in matrix form)
